-- Animation range type, used on Spritesheets
global AnimationRange = @record{
  fps: number,   -- frames per second of this animation
  from: usize,   -- first frame
  to: usize,     -- last frame
  loop: boolean, -- should animation loop?
}

-- checks equality between animation ranges
function AnimationRange.__eq(l: AnimationRange, r: AnimationRange): boolean
  return l.from == r.from and l.to == r.to and l.fps == r.fps
end
