-- The `Rectf` is just a convenient alias for `Rectn(number)`

-- Copyright (c) 2021-2022 André Luiz Alvares
-- Nene is licensed under the Zlib license.
-- Please refer to the LICENSE file for details
-- SPDX-License-Identifier: Zlib

local Rectn = require 'nene.math.rectn'

--[[
Alias of `Rectn(number)`.

Related Nene documentation:
* [Rectn](rectn.md#rectn)
]]
local Rectf: type = @Rectn(number)

return Rectf
