-- The `Rect` is just a convenient alias for `Rectn(integer)`

-- Copyright (c) 2021-2022 André Luiz Alvares
-- Nene is licensed under the Zlib license.
-- Please refer to the LICENSE file for details
-- SPDX-License-Identifier: Zlib

local Rectn = require 'nene.math.rectn'

--[[
Alias of `Rectn(integer)`.

Related Nene documentation:
* [Rectn](rectn.md#rectn)
]]
local Rect: type = @Rectn(integer)

return Rect
