-- The `Vec2i` is just a convenient alias for `Vec2n(integer)`

--[[
Copyright (c) 2021-present André Luiz Alvares
Nene is licensed under the Zlib license.
Please refer to the LICENSE file for details
SPDX-License-Identifier: Zlib
]]

local Vec2n = require 'nene.math.vec2n'

--[[
Alias of `Vec2n(integer)`.

Related Nene documentation:
* [Vec2n](vec2n.md#vec2n)
]]
local Vec2i: type = @Vec2n(integer)

return Vec2i
