-- The `Vec2` is just a convenient alias for `Vec2n(number)`

--[[
Copyright (c) 2021-present André Luiz Alvares
Nene is licensed under the Zlib license.
Please refer to the LICENSE file for details
SPDX-License-Identifier: Zlib
]]

local Vec2n = require 'nene.math.vec2n'

--[[
Alias of `Vec2n(number)`.

Related Nene documentation:
* [Vec2n](vec2n.md#vec2n)
]]
local Vec2: type = @Vec2n(number)

return Vec2
