-- Wraps all audio modules.

-- Copyright (c) 2021-2022 André Luiz Alvares
-- Nene is licensed under the Zlib license.
-- Please refer to the LICENSE file for details
-- SPDX-License-Identifier: Zlib

local Audio = @record{}

-- [Sound module](sound.md)
global Audio.Sound: type = require 'nene.audio.sound'
-- [Music module](music.md)
global Audio.Music: type = require 'nene.audio.music'

return Audio
